title: theDIG95
subtitle: Coding Experiments
description: This is my personal blog to showcase my experiments and projects
author: Saad Hasib
email: saadhasib@outlook.com
avatar: assets/images/avatar.png

baseurl: "/"
url: "https://thedig95.github.io"

github_url: "https://github.com/theDIG95"

google_analytics:

# Theme settings
theme: jekyll-theme-prologue
collections: [sections]
